name: relocata
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-184.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5
  ar_flutter_plugin_2:
    git:
      url: https://github.com/hlefe/ar_flutter_plugin_2.git
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_speed_dial: ^7.0.0
  uuid: ^4.1.0
  intl: ^0.18.1
  share_plus: ^7.2.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/relocata_icon.png"
  min_sdk_android: 21
